In [1]:
from dataread import DataRead
#important parts
# self.batch_num
# self.batch_size
# self.target_images eredeti kép
# self.cropped_images kivágott kép
# self.crop_images kivágott rész
# self.result_images majd ide lehet tenni a háló kimenetelét
# self.csv

In [2]:
train = DataRead(r'C:\\places\\','train',25,5)#path, mode, batch size, batch num  folder_path, data_type, batch_size, batch_num)

172703
172703
172703


In [3]:
print(train.target_images.shape)

(5, 25, 64, 64, 3)


In [4]:
print(train.cropped_images.shape)

(5, 25, 64, 64, 3)


In [5]:
print(train.crop_images.shape)


(5, 25, 28, 28, 3)


In [6]:
print(train.result_images.shape)

(5, 25, 64, 64, 3)


In [3]:
train.reset() #újra tölti

172703
172703
172703


In [7]:
train.make_masks()
print(train.cropped_images.shape)

63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
(5, 25, 64, 64, 4)


In [6]:
import csv

In [16]:

with open("out_train.csv", "r") as infile:
    r = csv.reader(infile)
    for i in range(8): # count from 0 to 7
        row = next(r)
        row = row[1:]
        row = list(map(int, row))
        print(row)
            

[106, 39, 197, 106]
[145, 118, 233, 191]
[146, 85, 231, 151]
[140, 134, 207, 212]
[53, 104, 139, 202]
[42, 81, 129, 161]
[101, 95, 170, 171]
[147, 42, 234, 132]


In [9]:
import numpy as np
test = np.ones((4,3))
print(test)
test = np.pad(test,((3,1),(2,1)))
print(test)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
test = np.ones((4,4,3))
insert = np.ones((1,2))
insert = np.pad(insert,((2,1),(1,1)))
print(insert)
print(test)
test = np.insert(test, 3, insert, axis=2)
#print(test.shape)
#print(test)
print(test[:,:,3])


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [22]:
import numpy as np
test = np.ones((3,4,2,2,1))
insert = np.zeros((3,4,2,2))

test = np.insert(test, 1, insert, axis=4)
print(test.shape)

(3, 4, 2, 2, 2)
