In [1]:
from dataread import DataRead
#important parts
# self.batch_num
# self.batch_size
# self.target_images eredeti kép
# self.cropped_images kivágott kép
# self.crop_images kivágott rész
# self.result_images majd ide lehet tenni a háló kimenetelét
# self.csv

In [2]:
train = DataRead(r'C:\\places\\','train',1,5)#path, mode, batch size, batch num  folder_path, data_type, batch_size, batch_num)

172703
172703
172703


In [4]:
print(train.target_images.shape)



(5, 1, 64, 64, 3)
(5, 1, 64, 64, 3)


In [5]:
print(train.cropped_images.shape)
train.make_masks()
print(train.cropped_images.shape)

(5, 1, 64, 64, 4)
(5, 1, 64, 64, 4)


In [22]:
print(train.csv[0])


[[23, 3, 48, 27, 22, 1, 49, 28]]


In [6]:
print(train.result_images.shape)

(5, 25, 64, 64, 3)


In [3]:
train.reset() #újra tölti

172703
172703
172703


In [7]:

#print(train.cropped_images.shape)

63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
63 63
(5, 25, 64, 64, 4)


In [6]:
import csv

In [16]:

with open("out_train.csv", "r") as infile:
    r = csv.reader(infile)
    for i in range(8): # count from 0 to 7
        row = next(r)
        row = row[1:]
        row = list(map(int, row))
        print(row)
            

[106, 39, 197, 106]
[145, 118, 233, 191]
[146, 85, 231, 151]
[140, 134, 207, 212]
[53, 104, 139, 202]
[42, 81, 129, 161]
[101, 95, 170, 171]
[147, 42, 234, 132]


In [9]:
import numpy as np
test = np.ones((4,3))
print(test)
test = np.pad(test,((3,1),(2,1)))
print(test)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
test = np.ones((4,4,3))
insert = np.ones((1,2))
insert = np.pad(insert,((2,1),(1,1)))
print(insert)
print(test)
test = np.insert(test, 3, insert, axis=2)
#print(test.shape)
#print(test)
print(test[:,:,3])


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [22]:
import numpy as np
test = np.ones((3,4,2,2,1))
insert = np.zeros((3,4,2,2))

test = np.insert(test, 1, insert, axis=4)
print(test.shape)

(3, 4, 2, 2, 2)


# Network example

In [73]:
import tensorflow as tf

class CNN(tf.keras.Model):
    def __init__(self, pic_size):
        super(CNN, self).__init__()
        
        self.c1_1 = tf.keras.layers.Conv2D(8,3,input_shape=(pic_size, pic_size, 4),activation='relu',padding="same")
        self.c1_2 = tf.keras.layers.Conv2D(16,3,activation='relu',padding="same")
        
        self.p1 = tf.keras.layers.Conv2D(32,3,strides=2,activation='relu',padding="same")
        self.p2 = tf.keras.layers.Conv2D(64,3,strides=2,activation='relu',padding="same")
        
        self.c2_1 = tf.keras.layers.Conv2D(128,3,activation='relu',padding="same")
        self.c2_2 = tf.keras.layers.Conv2D(128,3,activation='relu',padding="same")
        
        self.p3 = tf.keras.layers.Conv2DTranspose(64,3, strides=2,activation='relu',padding="same")
        self.p4 = tf.keras.layers.Conv2DTranspose(32,3, strides=2,activation='relu',padding="same")
        
        self.c3_1 = tf.keras.layers.Conv2D(16,3,activation='relu',padding="same")
        self.c3_2 = tf.keras.layers.Conv2D(3,3,activation='relu',padding="same")
        
        
    def call(self, inp, pic_size):
        x = inp
        mask = inp[0,:,:,3]
        
        
        x=self.c1_1(x)
        x=self.c1_2(x)
        
        x=self.p1(x)
        x=self.p2(x)
        
        x=self.c2_1(x)
        x=self.c2_2(x)
        
        x=self.p3(x)
        x=self.p4(x)
        
        x=self.c3_1(x)
        x=self.c3_2(x)
        
        #x =tf.math.multiply(x*mask)
        # x [batch_size, x,y,3]
        print(x.shape)
        
        whole = inp
        
        #whole = tf.convert_to_tensor(inp)
        #whole = x[]
        crop = x[0,10:20+1, 10:20+1,:]
        #crop = whole[1,pic_size[4]:pic_size[6]+1, pic_size[5]:pic_size[7]+1,3]
        whole[0,10:20+1, 10:20+1,:]  = crop
        crop = whole[0,10:23+1, 10:23+1,:] 
        
        return whole, crop
        
       

In [74]:
network = CNN(64)
predictions = network(train.cropped_images[0],train.csv[0])

(1, 64, 64, 3)


TypeError: in converted code:

    <ipython-input-73-0f36d5946b47>:53 call
        whole[0,10:20+1, 10:20+1,:]  = crop

    TypeError: 'Tensor' object does not support item assignment


In [61]:
import numpy as np
tensor = tf.convert_to_tensor(train.cropped_images[0])
print(tensor[0,0:10,0,1])

print(train.cropped_images.shape)
mask = train.cropped_images[0,0,:,:,3]
print(mask.shape)
masks = np.array([[mask],[mask],[mask]])
print(masks.shape)

Tensor("strided_slice_10:0", shape=(10,), dtype=float64)
(5, 1, 64, 64, 4)
(64, 64)
(3, 1, 64, 64)


In [ ]:
x = tf.keras.backend.ones((16, 64))
y = tf.keras.backend.ones((64, 16))
xy = tf.keras.backend.dot(x, y)

In [ ]:
#lr_schedule= tf.keras.optimizers.schedules.ExponentialDecay(1e-5, decay_steps=10000, decay_rate=0.5,staircase=True)#====
#lr_schedule= tf.keras.optimizers.schedules.InverseTimeDecay(1e-5, decay_steps=3000, decay_rate=9,staircase=True)#====

#optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule, beta_1=0.9, beta_2=0.98, epsilon=1e-9, )#======
#optimizer = tf.keras.optimizers.Adam(learning_rate=1e-5, beta_1=0.9, beta_2=0.98, epsilon=1e-9, )

optimizer = tf.keras.optimizers.Nadam(1e-5, beta_1=0.9, beta_2=0.98, epsilon=1e-9, )

In [ ]:
def loss_function(real, pred):
    #return tf.reduce_mean(tf.math.square(real-pred))  #========
    return tf.reduce_sum(tf.math.square(real-pred))

train_loss = tf.keras.metrics.Mean(name='train_loss')


In [ ]:
transformer = CNN3(in_seq_len,input_size,target_size)

In [ ]:
checkpoint_path = "./checkpoints/train"

ckpt = tf.train.Checkpoint(transformer=transformer, optimizer=optimizer)

ckpt_manager = tf.train.CheckpointManager(ckpt, checkpoint_path, max_to_keep=5)

'''
if ckpt_manager.latest_checkpoint:
    ckpt.restore(ckpt_manager.latest_checkpoint)
    print("Checkpoint restored")
''';

In [ ]:
train_step_signature =  [
    tf.TensorSpec(shape=(None, None, input_size), dtype=tf.float32),
    tf.TensorSpec(shape=(None, 1, target_size), dtype=tf.float32)
    ]

@tf.function(input_signature=train_step_signature)
def train_step(inp, tar):
    with tf.GradientTape() as tape:
        predictions = transformer(inp)

        
        loss = loss_function(tar, predictions)
    
    gradients = tape.gradient(loss, transformer.trainable_variables)
    optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))
    #optimizer.step()
    
    train_loss(loss)

In [ ]:
# Training and feedback
losses=[]
#======

for epoch in range(epochs):
    stime = time.time()
    
    xp=0 #=======
    yp=0
    zp=0
    tp=0
    w=0
    
    train_loss.reset_states()
    h=0
    for batch in range(X.shape[0]):
        inp = X[batch]
        tar = Y[batch]
        
        #========
        xprec, yprec, zprec, truprec, whole = precision_function(inp, tar, 0.005)
        xp+=xprec
        yp+=yprec
        zp+=zprec
        tp+=truprec
        w+=whole
        
        train_step(inp, tar)
        
        if batch % 50 ==0:
            print('Epoch {} Batch {} Loss {:.5f}'.format(
            epoch+1, batch, train_loss.result()
            ))
            
    
    print('Epoch {} Precisions: x:{:.2f} %, y:{:.2f} %, z:{:.2f} %'.format(epoch+1, xp/w*100 , yp/w*100, zp/w*100)) #========
    print('Epoch {} True Precisions: {:.2f} %'.format(epoch+1, tp/w*100)) 
    
    if (epoch+1) %5 ==0:
        ckpt_save_path = ckpt_manager.save()
        print ('Saving checkpoint for epoch {} at {}'.format(epoch+1,
                                                         ckpt_save_path))
   
    
    print ('Epoch {} Loss {:.5f}'.format(epoch + 1,  train_loss.result()))
    losses.append(train_loss.result())#=====

    print ('Time taken for 1 epoch: {} secs\n'.format(time.time() - stime))
#========
timel=np.arange(epochs)+1
plt.plot(timel,losses)